# Indexing and slicing

Lets now learn about indexing and slicing in Numpy

## Indexing (Same as Python Lists)

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


## Slicing (Extracting Parts of an Array)

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


## Slicing returns a view, not a copy! Changes affect the original array.**

This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

**Why does this happen?**

* *Memory Efficiency:* Avoids unnecessary copies, making operations faster and saving memory.
* *Performance: Enables* faster access and manipulation of large datasets without duplicating data.

In [5]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


**Use `.copy()` if you need an independent copy.**

## Fancy Indexing & Boolean Masking

### Fancy Indexing (Select Multiple Elements)

In [6]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


### Boolean Masking (Filter Data)

In [7]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


This is a powerful way to filter large datasets efficiently!

## Summary
* **NumPy arrays** are faster, memory-efficient alternatives to lists.
* You can create arrays using `np.array()`, `np.zeros()`, `np.ones()`, etc.
* **Indexing & slicing** allow efficient data manipulation.
* **Reshaping & flattening** change array structures without copying data.
* **Fancy indexing & boolean** masking help filter and access specific data.

## Exercises for Practice

1. Create a 3×3 array filled with random numbers and print its shape.

In [17]:
arr = np.random.rand(3,3)
print("Array:\n",arr)

Array:
 [[0.86153754 0.60030308 0.37247976]
 [0.68320519 0.9150774  0.59412534]
 [0.07818888 0.0135271  0.10801715]]


In [18]:
print("Array Shape:\n", arr.shape)

Array Shape:
 (3, 3)


2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [21]:
arr = np.array([1.1, 2.2, 3.3]).astype('int64')
arr

array([1, 2, 3])

3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
mask = arr % 2 == 0

In [25]:
arr[mask]

array([2, 4, 6])

4. Reshape a 1D array of size 9 into a 3×3 matrix

In [26]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

5. Use boolean masking to filter numbers greater than 50 in an array.

In [28]:
arr = np.array([25, 60, 45, 80, 35, 90, 50])

In [33]:
mask = arr>50

In [34]:
result = arr[mask]

print(result)

[60 80 90]
