## Why use NumPy

**Python lists are flexible but slow for numerical computing because they:**
* Store elements as pointers instead of a continuous block of memory.
* Lack vectorized operations, relying on loops instead.
* Have significant overhead due to dynamic typing.

## NumPy's Superpowers:
* Faster than Python lists (C-optimized backend)
* Uses less memory (efficient storage)
* Supports vectorized operations (no explicit loops needed)
* Has built-in mathematical functions

----------------------
## NumPy vs. Python Lists – Performance Test

Let's compare Python lists with NumPy arrays using a simple example.

### Example 1: Adding Two Lists vs. NumPy Arrays

In [1]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

Python list addition time: 0.08521914482116699
NumPy array addition time: 0.024292945861816406


**Key Takeaway:** NumPy is significantly faster because it performs operations in C, avoiding Python loops.

-------------
## Creating NumPy Arrays

In [3]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

print("\n---------------")

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

print("\n---------------")

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

print("\n---------------")

[1 2 3 4 5]

---------------
[[1 2 3]
 [4 5 6]]

---------------
Type: <class 'numpy.ndarray'>
Shape: (2, 3)

---------------


__NumPy stores data in a contiguous memory block, making access faster than lists. shape shows the dimensions of an array.__

--------------
## Memory Efficiency – NumPy vs. Lists

Let's check memory consumption.

In [4]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


**NumPy arrays use significantly less memory** compared to Python lists.

---------
## Vectorization – No More Loops!

NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

### Example 2: Squaring Elements

In [5]:
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2

**NumPy is cleaner and faster!**

-------------
## Summary

* NumPy is **faster** than Python lists because it is optimized in **C**.
* It consumes **less memory** due to efficient storage.
* It provides **vectorized operations**, removing the need for slow loops.
* Essential for **data science** and **machine learning workflows.**

------
## Exercises for Practice

### Create a NumPy array with values from 10 to 100 and print its shape.


In [18]:
arr = np.arange(10,101)

In [19]:
print("Shanpe :",arr.shape)

Shanpe : (91,)


### Compare the time taken to multiply two Python lists vs. two NumPy arrays.

In [16]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x * y for x, y in zip(list1, list2)]
end = time.time()
print("Python list multiply time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 * arr2  # Vectorized operation
end = time.time()
print("NumPy array multiply time:", end - start)

Python list multiply time: 0.1321554183959961
NumPy array multiply time: 0.016855239868164062


### Find the memory size of a NumPy array with 1 million elements.

In [17]:
import sys

list_data = list(range(1_000_000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8000056000000 bytes
NumPy array size: 8000000 bytes
