# Model Evaluation & Tuning : GridSearchCV

In [1]:
#Import necessary library
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
#Load Dataset

iris = load_iris()
X,y = iris.data, iris.target
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [3]:
y[:5]

array([0, 0, 0, 0, 0])

In [4]:
#Pipeline : Scaling + Classifier
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter = 500))
])

In [5]:
#Define Hyperparameter Grid

param_grid = {
    "clf__penalty" : ["l1","l2"],
    "clf__C" : [0.01,0.1,1,10],
    "clf__solver": ["liblinear"]
}


In [6]:
#GridSearch setup

grid = GridSearchCV(
    estimator = pipe,
    param_grid = param_grid,
    cv =5,
    scoring = "accuracy",
    refit = True,
    n_jobs = -1
)

In [7]:
#Run the grid Search
grid.fit(X,y)

print("Best Parameters:", grid.best_params_)
print("Best Cross-validation Accuracy:", grid.best_score_)
print("Test Accuracy with Best Model:", grid.score(X,y))

Best Parameters: {'clf__C': 10, 'clf__penalty': 'l1', 'clf__solver': 'liblinear'}
Best Cross-validation Accuracy: 0.9533333333333334
Test Accuracy with Best Model: 0.9666666666666667


C:\Users\C5144878\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(


## Python Code Example 1 : Logistic Regression(simple)

In [8]:
#Import necessary library
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [9]:
#Load Dataset

iris = load_iris()
X,y = iris.data, iris.target
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
y[:5]

array([0, 0, 0, 0, 0])

In [11]:
#Pipeline : Scaling + Classifier
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter = 500))
])

In [12]:
#Define Hyperparameter Grid

param_grid = {
    "clf__penalty" : ["l1","l2"],
    "clf__C" : [0.01,0.1,1,10],
    "clf__solver": ["liblinear"]
}


In [13]:
#GridSearch setup

grid = GridSearchCV(
    estimator = pipe,
    param_grid = param_grid,
    cv =5,
    scoring = "accuracy",
    refit = True,
    n_jobs = -1
)
grid.fit(X,y)

C:\Users\C5144878\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(


,estimator,Pipeline(step...x_iter=500))])
,param_grid,"{'clf__C': [0.01, 0.1, ...], 'clf__penalty': ['l1', 'l2'], 'clf__solver': ['liblinear']}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,copy,True


In [14]:
print("Best Parameters:", grid.best_params_)
print("Best Cross-validation Accuracy:", grid.best_score_)
print("Test Accuracy with Best Model:", grid.score(X,y))

Best Parameters: {'clf__C': 10, 'clf__penalty': 'l1', 'clf__solver': 'liblinear'}
Best Cross-validation Accuracy: 0.9533333333333334
Test Accuracy with Best Model: 0.9666666666666667


In [15]:
##Example 2 - RandomForest (practical, Breast Cancer Dataset)

from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV


In [16]:
#Load Datasets
data = load_breast_cancer()
X,y = data.data, data.target
X[:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [17]:
#Define base Model

rf = RandomForestClassifier(random_state=42)

#Define hyperparameter grid to tune
param_grid = {
    "n_estimators" :[50,100,200],
    "max_depth": [None, 5,10],
    "min_samples_split":[2,5,10],
    "min_samples_leaf":[1,2,4]
}

In [18]:
#Define CS Strategy
cv = StratifiedKFold(
    n_splits=5, 
    shuffle = True, 
    random_state =42
)

In [19]:
#GridSearch setup

grid = GridSearchCV(
    estimator = rf,
    param_grid = param_grid,
    cv =cv,
    scoring = "roc_auc",
    refit = True,
    n_jobs = -1,
    verbose =1
)
grid.fit(X,y)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


,estimator,RandomForestC...ndom_state=42)
,param_grid,"{'max_depth': [None, 5, ...], 'min_samples_leaf': [1, 2, ...], 'min_samples_split': [2, 5, ...], 'n_estimators': [50, 100, ...]}"
,scoring,'roc_auc'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo... shuffle=True)
,verbose,1
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_estimators,100


In [20]:
print("Best Parameters:", grid.best_params_)
print("Best Mean ROC-AUC(CV):", grid.best_score_)
print("Final  ROC-AUC  with Best Model:", grid.score(X,y))

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 100}
Best Mean ROC-AUC(CV): 0.991355367346196
Final  ROC-AUC  with Best Model: 0.9987315680989376


## Observation

* We used GridSearchCV to systematically tune the hyperparameters of a Random Forest model.

* GridSearchCV tested 81 different parameter combinations, each with 5-fold cross-validation, giving a total of 405 fits.

* The best parameters it found were: max_depth=5, min_samples_leaf=2, min_samples_split=10, n_estimators=100.

* With these parameters, the model achieved an excellent mean ROC-AUC of ~0.991 during cross-validation, and after retraining on the entire dataset, the final ROC-AUC reached ~0.999.

## Summary & Takeaways

* **Cross-Validation (Part 1):** Reliable way to evaluate model performance.
* **GridSearchCV (Part 2):** Uses CV internally to find the best hyperparameters.
* **Example with Logistic Regression and Random Forest showed:**
    * How to define parameter grids.
    * How `GridSearchCV` automates training/testing for all combinations.
    * How to interpret the best parameters and final scores.

### Takeaway
Cross-Validation helps us evaluate models, and GridSearchCV builds on that to *tune* them. Together, they are essential tools for building reliable, high-performing machine learning models.

## Cross-Validation vs. GridSearchCV

To understand the workflow used in this project, here is a direct comparison of how the model was evaluated versus how it was tuned:

| Aspect | Cross-Validation (Part 1) | GridSearchCV (Part 2) |
| :--- | :--- | :--- |
| **Purpose** | Evaluate model performance reliably | Tune model hyperparameters systematically |
| **What it does** | Splits dataset into $k$ folds, trains on $k-1$, tests on 1, repeats | Tries all parameter combinations, uses CV for each, finds best |
| **Output** | Mean $\pm$ std of chosen metric (accuracy, recall, etc.) | Best hyperparameter set + best CV score |
| **Focus** | Generalization ability | Optimization of parameters |
| **When to use** | Anytime you want robust evaluation | When model performance depends heavily on hyperparameters |
| **Example** | Logistic Regression evaluated with 10-fold CV | Random Forest tuned with 81 parameter combinations |