## Introduction to NumPy (Numerical Python)

What is NumPy?

NumPy (Numerical Python) is a powerful library for numerical and scientific computing in Python.

Features of NumPy

- Faster than lists (because it uses contiguous memory allocation).

- Supports multidimensional arrays (Ndarrays).

- Optimized for mathematical and statistical operations.

- Used in many fields like Data Science, Machine Learning, and almost all domains from Finance to Insurance.



In [30]:
import numpy as np

import time

lst = list(range(1000000))

arr = np.arange(1000000)

start = time.time()

sum(lst)

print("List time:", time.time() - start)

start = time.time()
np.sum(arr)
print("NumPy time:", time.time() - start)


List time: 0.009969949722290039
NumPy time: 0.0008797645568847656


## Ndarray – The Heart of NumPy

### What is an Ndarray?

An Ndarray (N-dimensional array) is the fundamental data structure in NumPy.

It is a homogeneous collection of data stored in a grid format.

 ### Creating Arrays

In [31]:
# 1D Array

In [32]:
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

1D Array: [1 2 3 4]


In [33]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)



2D Array:
 [[1 2 3]
 [4 5 6]]


In [34]:
# Array of zeros, ones, range
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)



Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
ones = np.ones((3, 3))
print("Ones:\n", ones)


Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:

range_array = np.arange(0, 10, 2)
print("Range array:", range_array)


Range array: [0 2 4 6 8]


### Array Operations

In [37]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([10, 20, 30])

# Element-wise operations
print("Addition:", arr_a + arr_b) # 1 vs 8

print("Multiplication:", arr_a * arr_b)

print("Squared:", arr_a ** 2)


Addition: [11 22 33]
Multiplication: [10 40 90]
Squared: [1 4 9]


In [38]:
# Broadcasting
matrix = np.array([[1, 2], [3, 4]])

print("original matrix\n",matrix)
print()
print("Add scalar 5:\n", matrix + 5)

original matrix
 [[1 2]
 [3 4]]

Add scalar 5:
 [[6 7]
 [8 9]]


###  Indexing, Slicing, Reshaping

In [39]:

arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", arr)
print()

# Indexing
print("Element [0,1]:", arr[0, 1])

# Indexing
print("Element [1,2]:", arr[1, 2])


Original array:
 [[10 20 30]
 [40 50 60]]

Element [0,1]: 20
Element [1,2]: 60


In [40]:
# Slicing
print("First row:", arr[0, :])
print()
print("Last column:", arr[:, -1])


First row: [10 20 30]

Last column: [30 60]


In [41]:
# Reshaping
reshaped = np.arange(12).reshape(3, 4)
print("Reshaped (3x4):\n\n", reshaped)

Reshaped (3x4):

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Useful NumPy Functions

In [42]:
arr = np.array([4, 7, 2, 8, 3])
print("Mean:", np.mean(arr))


Mean: 4.8


In [43]:
print("Standard Deviation:", np.std(arr))



Standard Deviation: 2.3151673805580453


In [44]:
print("Sorted:", np.sort(arr))

Sorted: [2 3 4 7 8]


In [45]:
lin = np.linspace(0, 1, 5)
print("Linspace 0 to 1:", lin)

Linspace 0 to 1: [0.   0.25 0.5  0.75 1.  ]


In [46]:
# Random
rand = np.random.randint(1, 10, (2, 3))
print("Random Integers (2x3):\n", rand)

Random Integers (2x3):
 [[2 8 2]
 [4 8 9]]


### Quiz Time


#### **Q1.** Create a 5x5 matrix with values from 1 to 25


In [47]:
mat = np.arange(1, 26).reshape(5, 5)
print("5x5 Matrix:\n", mat)


5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]



#### **Q2.** Get middle 3x3 matrix



In [48]:
mid = mat[1:4, 1:4]
print("Middle 3x3:\n", mid)


Middle 3x3:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



#### **Q3.** Sum of each row



In [49]:
row_sum = np.sum(mat, axis=1)
print("Row-wise sum:", row_sum)


Row-wise sum: [ 15  40  65  90 115]


In [50]:
col_sum = np.sum(mat, axis=0)
print("Column-wise sum:", col_sum)

Column-wise sum: [55 60 65 70 75]


### Case study – Insurance Claim Records using numpy

*Consider an insurance company analyzing monthly claims made by policyholders:*

In [51]:
import numpy as np  

# Monthly claim amounts (in INR) for different policyholders
claims = np.array([
    [12000, 15000, 18000],  # Policyholder 1
    [10000, 13000, 17000],  # Policyholder 2
    [9000,  11000, 16000]   # Policyholder 3
])

print("Insurance Claim Data (INR):")
print(claims)



Insurance Claim Data (INR):
[[12000 15000 18000]
 [10000 13000 17000]
 [ 9000 11000 16000]]


In [52]:
# Accessing Elements in an Ndarray
# Access claim amount of Policyholder 3 for the first month
print("Claim amount for Policyholder 3 in Month 1:", claims[2, 0])  
print("Claim amount for Policyholder 1 in Month 3:", claims[0, 2])  


Claim amount for Policyholder 3 in Month 1: 9000
Claim amount for Policyholder 1 in Month 3: 18000


### Array Operations in NumPy

In [53]:
# NumPy allows performing operations on entire arrays efficiently.

# Example – Total Claim Amount Per Policyholder

# Calculate total claim per policyholder
total_claims = np.sum(claims, axis=1) #1 for row wise , 0 for column wise
print("Total claims per policyholder:", total_claims)



Total claims per policyholder: [45000 40000 36000]


In [54]:
print(claims)

[[12000 15000 18000]
 [10000 13000 17000]
 [ 9000 11000 16000]]


In [55]:
#Example – Average Claim Amount per Month
# Average claim amount per month across all policyholders

avg_claims = np.mean(claims, axis=0)
print("Average claim per month:", avg_claims)



Average claim per month: [10333.33333333 13000.         17000.        ]


In [56]:
# Example – Identify High-Value Claims (above INR 15,000)
# Find claims greater than 15,000 INR

high_value_claims = claims[claims > 15000]
print("High-value claims:", high_value_claims)


High-value claims: [18000 17000 16000]


**Why Use NumPy for Insurance Data Analytics?**

- Speeds up data processing in large datasets.

- Efficiently handles numerical data (e.g., premium amounts, claim settlements).

- Reduces memory usage compared to Python lists.

- Supports advanced statistical operations required for fraud detection and risk modeling.