# Assignment 1 - Working with NumPy

## Objective: Understand the basics of NumPy, array creation, and manipulation.


## Instructions

### Step 1 : Install NumPy using

In [42]:
#!pip install numpy


### Step 2 : Create a new Python script numpy_assignment.ipynb. Import NumPy and follow these steps:

In [43]:
import numpy as np

#### 1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations: 

In [44]:
arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


####   a. Calculate the sum, mean, median, and standard deviation of the elements in the array. 

In [45]:
sum_arr1 = np.sum(arr1)
print("Sum of arr1:", sum_arr1)

Sum of arr1: 210


In [46]:
mean_arr1 = np.mean(arr1)
print("Mean of arr1:", mean_arr1)

Mean of arr1: 10.5


In [47]:
median_arr1 = np.median(arr1)
print("Median of arr1:", median_arr1)

Median of arr1: 10.5


In [48]:
std_arr1 = np.std(arr1)
print("Standard Deviation of arr1:", std_arr1)

Standard Deviation of arr1: 5.766281297335398


####  b. Find the indices of elements greater than 10 in the array.

In [49]:
greater_than_10 = arr1[arr1 > 10]
print(f" Indices of elements greater than 10 in arr1:\n{greater_than_10}")

 Indices of elements greater than 10 in arr1:
[11 12 13 14 15 16 17 18 19 20]


### 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.

In [50]:
arr2 = np.arange(1, 17).reshape(4, 4)

#### a. Print the array.

In [51]:
print(f"2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16:\n{arr2}")

2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


####  b. Find the transpose of the array.

In [52]:
arr2_t = np.transpose(arr2)
print(f"The transpose of the arr2 is :\n{arr2_t}")

The transpose of the arr2 is :
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


#### c. Calculate the row-wise and column-wise sums of the array.

In [53]:
sum_of_row = np.sum(arr2, axis = 1)
print(f"Sum of row of arr2: {sum_of_row}")

Sum of row of arr2: [10 26 42 58]


In [54]:
sum_of_column = np.sum(arr2, axis = 0)
print(f"Sum of column of arr2: {sum_of_column}")

Sum of column of arr2: [28 32 36 40]


### 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.

In [55]:
rand_arr1 = np.random.randint(1,20, (3,3))
print(rand_arr1)

[[ 3 12  6]
 [11  9  6]
 [10  1  2]]


In [56]:
rand_arr2 = np.random.randint(1,20, (3,3))
print(rand_arr2)

[[10 16  9]
 [ 6 10  8]
 [11 12 16]]


#### a. Perform element-wise addition, subtraction, and multiplication.

In [57]:
print(f"element-wise addition:\n {rand_arr1 + rand_arr2}")

element-wise addition:
 [[13 28 15]
 [17 19 14]
 [21 13 18]]


In [58]:
print(f"element-wise subtraction:\n {rand_arr1 - rand_arr2}")

element-wise subtraction:
 [[ -7  -4  -3]
 [  5  -1  -2]
 [ -1 -11 -14]]


In [59]:
print(f"element-wise multiplication:\n {rand_arr1 * rand_arr2}")

element-wise multiplication:
 [[ 30 192  54]
 [ 66  90  48]
 [110  12  32]]


#### b. Compute the dot product of the two arrays.

In [60]:
dot_rand = np.dot(rand_arr1, rand_arr2)
print(f"dot product of the two arrays:\n {dot_rand}")

dot product of the two arrays:
 [[168 240 219]
 [230 338 267]
 [128 194 130]]


### 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns. 

In [62]:
arr1d = np.arange(1,13)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
reshape_arr1d = arr1d.reshape(3,4)
reshape_arr1d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
print(f"Fist two rows:\n {reshape_arr1d[0:2,]}")

Fist two rows:
 [[1 2 3 4]
 [5 6 7 8]]


In [71]:
print(f"Last two columns:\n {reshape_arr1d[:,2:]}")

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
